### ISSUE TITLE
LINEアカウントのリッチメニューを作ってほしい🥺

### ISSUE THREAD

**Issue by putcho01** [HackU-NFP/HackU-NFP-Front#3]
### 1. リッチメニューのデザイン作成 
横2500 x たて843 px
こんな感じで3つのボタンがあるデザインを作ってほしい
NFTを作成 | NFTを見る | 使い方

![スクリーンショット 2022-02-17 6 59 49](https://user-images.githubusercontent.com/53213591/154364490-f622cba0-22ac-446b-8452-314b7239e582.png)

![richmenu](https://user-images.githubusercontent.com/53213591/154364396-1200b852-8d37-41c4-b718-4c7d13ff3bd2.png)

### 2. 作ったリッチメニューの設定
ここから設定 -> https://manager.line.biz/account/@507dmdzo/richmenu/create
- 一番左は NFTの作成ボタンにする。押すと"NFTを作成する"というテキストが送信されるようにactionを設定してほしいです。
- 真ん中のボタンはリンクを設定してほしいです。https://wallet.bitmax.me/coins
- 一番右は"使い方"というテキストが送信されるようにする

**Comment by RU-II** [comment]
デザインはともかく作成しました
![S__324009998](https://user-images.githubusercontent.com/76895201/154500021-acc5ea9b-01a0-4cbb-aedc-ec7a3dbe1184.jpg)

**Comment by RU-II** [comment]
ニューモーフィズム
https://qiita.com/youx_/items/cf421639d6b750e3c4ec
![nfp_rich_menu_ver 2 0](https://user-images.githubusercontent.com/76895201/154515655-75c72205-5899-4ebd-9b50-83ed783b52c8.png)
